disabled_rules:
  - trailing_whitespace
  - file_length
opt_in_rules:
  - empty_count
excluded:
  - Example/Pods/OHHTTPStubs
  - Example/Pods/ReachabilitySwift
  - Example/Pods
  - _Pods.xcodeproj
reporter: "xcode"
type_name:
    excluded:
        - T
    max_length:
        warning: 45
        error: 50
